### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by jiaojianz** [xxydrr/vue-koa-chat#1]
注册成功后，登录会提示“官方账号不存在”，但是还是登录进去了，添加好友会报错，因为“api/user/getOfficialInfo”这个接口没有返回数据，这个问题怎么解决？

**Comment by reeswell** [comment]
@jiaojianz 这个我在视频演示那里有说，就是需要在后端先执行npm run init初始化一个官方账号。

**Comment by jiaojianz** [comment]
> @jiaojianz 这个我在视频演示那里有说，就是需要在后端先执行npm run init初始化一个官方账号。

好的，谢谢。

**Comment by quboqin** [comment]
执行npm run init初始化, 但是还是登陆失败

**Comment by quboqin** [comment]
方便给一个联系方式吗

**Comment by xxydrr** [comment]
> 执行npm run init初始化, 但是还是登陆失败
现在可以了

**Comment by xxydrr** [comment]
@quboqin 现在可以了

**Comment by xxydrr** [comment]
> 执行npm run init初始化, 但是还是登陆失败

已修复
